apiVersion: v1
kind: Pod
metadata:
  name:  formation-ckad-empty-dir
  labels:
    app: my-hostpath
spec:
  containers:
  - image: busybox
    volumeMounts:
    - mountPath: /foo
      name: example-volume
      readOnly: false
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  - image: busybox
    volumeMounts:
    - mountPath: /bar
      name: example-volume
      readOnly: false
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox-2
  volumes:
  - name: example-volume
    emptyDir: {}
  restartPolicy: Always