apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fruits.test.fr ##  plurials.group
spec:
  group: test.fr
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nameFruit:
                  type: string
                typeFruit:
                  type: string
                  enum:
                  - noyau 
                  - pepins
                  - agrumes
                  - coque 
                  - exotiques
  scope: Namespaced
  names:
    plural: fruits
    singular: fruit
    kind: Fruit
    shortNames:
    - ft



