apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: ckad-formation-ingress
        image:  lbouquin/ckad-formation-ingress:0.0.22
        ports:
        - containerPort: 80
        env: 
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAME 
          value: "foo.test.fr"
