apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deploy
  labels:
    app: secret-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-deploy
  template:
    metadata:
      labels:
        app: secret-deploy
    spec:
      containers:
      - name: ckad-formation-ingress
        image:  lbouquin/ckad-formation-ingress:0.0.22
        ports:
        - containerPort: 80
        env: 
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAME 
          value: secret-deploy.test.fr.
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: monpremiersecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: monpremiersecret
              key: password