---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-ckad-serviceaccounts
  labels:
    app: formation-ckad-serviceaccounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  formation-ckad-serviceaccounts
  template:
    metadata:
      labels:
        app:  formation-ckad-serviceaccounts
    spec:
      serviceAccountName: monpremiersa
      containers:
      - name: curl
        image:   lbouquin/formation-ckad-general-image:0.0.1
        command:
          - sh
          - -c
          - |
            while true; do
              echo "Liste des services:" ; 
              curl -s --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
                --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
                https://kubernetes/api/v1/namespaces/default/services \
                |jq .items[].metadata.name
              echo ; 
              sleep 5;
            done