apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-ckad-probes
  labels:
    app: formation-ckad-probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formation-ckad-probes
  template:
    metadata:
      labels:
        app: formation-ckad-probes
    spec:
      containers:
      - name: ckad-formation-ingress
        image:  lbouquin/ckad-formation-ingress:0.0.23
        ports:
        - containerPort: 80
        env: 
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAME 
          value: bar.test.fr.
        startupProbe: 
            httpGet:
              path: /
              port: 80
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 5
        livenessProbe:
          exec:
            command:
            - cat
            - /usr/share/nginx/html/index.html
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 1